version: "3.3"

services:

  apache:
    build:
      context: ./docker-config
      dockerfile: PHPDockerfile
    restart: always
    container_name: apache
    volumes:
      - ./src:/var/www/html
    ports:
      - 80:80
    links:
      - mariadb
      - memcached

  mariadb:
    image: mariadb:10.4
    restart: always
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
    ports:
      - 3306:3306

  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: pma
    environment:
      - PMA_HOST=mariadb
      - PMA_PASSWORD=root
      - PMA_USER=root
    links:
      - mariadb
    ports:
      - 8080:80

  memcached:
    image: memcached
    restart: always
    container_name: memcached
    ports:
      - 11211:11211